---
abstract: 'provides: log_(debug,warn,info,error,fatal) with warn() like caller context'
author:
  - 'Samuel Kaufman <sam@socialflow.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Caller
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.02
